/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTasksIndexRouteImport } from './routes/api/tasks/index'
import { Route as ApiTagsIndexRouteImport } from './routes/api/tags/index'
import { Route as ApiStatusesIndexRouteImport } from './routes/api/statuses/index'
import { Route as ApiDailyReportsIndexRouteImport } from './routes/api/daily-reports/index'
import { Route as ApiTasksTaskIdRouteImport } from './routes/api/tasks/$taskId'
import { Route as ApiTagsTagIdRouteImport } from './routes/api/tags/$tagId'
import { Route as ApiStatusesStatusIdRouteImport } from './routes/api/statuses/$statusId'
import { Route as ApiDailyReportsDateRouteImport } from './routes/api/daily-reports/$date'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDailyReportsDateTasksRouteImport } from './routes/api/daily-reports/$date.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIndexRoute = ApiTasksIndexRouteImport.update({
  id: '/api/tasks/',
  path: '/api/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsIndexRoute = ApiTagsIndexRouteImport.update({
  id: '/api/tags/',
  path: '/api/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusesIndexRoute = ApiStatusesIndexRouteImport.update({
  id: '/api/statuses/',
  path: '/api/statuses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyReportsIndexRoute = ApiDailyReportsIndexRouteImport.update({
  id: '/api/daily-reports/',
  path: '/api/daily-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksTaskIdRoute = ApiTasksTaskIdRouteImport.update({
  id: '/api/tasks/$taskId',
  path: '/api/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsTagIdRoute = ApiTagsTagIdRouteImport.update({
  id: '/api/tags/$tagId',
  path: '/api/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusesStatusIdRoute = ApiStatusesStatusIdRouteImport.update({
  id: '/api/statuses/$statusId',
  path: '/api/statuses/$statusId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyReportsDateRoute = ApiDailyReportsDateRouteImport.update({
  id: '/api/daily-reports/$date',
  path: '/api/daily-reports/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyReportsDateTasksRoute =
  ApiDailyReportsDateTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => ApiDailyReportsDateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/daily-reports/$date': typeof ApiDailyReportsDateRouteWithChildren
  '/api/statuses/$statusId': typeof ApiStatusesStatusIdRoute
  '/api/tags/$tagId': typeof ApiTagsTagIdRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/daily-reports': typeof ApiDailyReportsIndexRoute
  '/api/statuses': typeof ApiStatusesIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
  '/api/tasks': typeof ApiTasksIndexRoute
  '/api/daily-reports/$date/tasks': typeof ApiDailyReportsDateTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/daily-reports/$date': typeof ApiDailyReportsDateRouteWithChildren
  '/api/statuses/$statusId': typeof ApiStatusesStatusIdRoute
  '/api/tags/$tagId': typeof ApiTagsTagIdRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/daily-reports': typeof ApiDailyReportsIndexRoute
  '/api/statuses': typeof ApiStatusesIndexRoute
  '/api/tags': typeof ApiTagsIndexRoute
  '/api/tasks': typeof ApiTasksIndexRoute
  '/api/daily-reports/$date/tasks': typeof ApiDailyReportsDateTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/daily-reports/$date': typeof ApiDailyReportsDateRouteWithChildren
  '/api/statuses/$statusId': typeof ApiStatusesStatusIdRoute
  '/api/tags/$tagId': typeof ApiTagsTagIdRoute
  '/api/tasks/$taskId': typeof ApiTasksTaskIdRoute
  '/api/daily-reports/': typeof ApiDailyReportsIndexRoute
  '/api/statuses/': typeof ApiStatusesIndexRoute
  '/api/tags/': typeof ApiTagsIndexRoute
  '/api/tasks/': typeof ApiTasksIndexRoute
  '/api/daily-reports/$date/tasks': typeof ApiDailyReportsDateTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/api/daily-reports/$date'
    | '/api/statuses/$statusId'
    | '/api/tags/$tagId'
    | '/api/tasks/$taskId'
    | '/api/daily-reports'
    | '/api/statuses'
    | '/api/tags'
    | '/api/tasks'
    | '/api/daily-reports/$date/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/api/daily-reports/$date'
    | '/api/statuses/$statusId'
    | '/api/tags/$tagId'
    | '/api/tasks/$taskId'
    | '/api/daily-reports'
    | '/api/statuses'
    | '/api/tags'
    | '/api/tasks'
    | '/api/daily-reports/$date/tasks'
  id:
    | '__root__'
    | '/'
    | '/api/auth/$'
    | '/api/daily-reports/$date'
    | '/api/statuses/$statusId'
    | '/api/tags/$tagId'
    | '/api/tasks/$taskId'
    | '/api/daily-reports/'
    | '/api/statuses/'
    | '/api/tags/'
    | '/api/tasks/'
    | '/api/daily-reports/$date/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDailyReportsDateRoute: typeof ApiDailyReportsDateRouteWithChildren
  ApiStatusesStatusIdRoute: typeof ApiStatusesStatusIdRoute
  ApiTagsTagIdRoute: typeof ApiTagsTagIdRoute
  ApiTasksTaskIdRoute: typeof ApiTasksTaskIdRoute
  ApiDailyReportsIndexRoute: typeof ApiDailyReportsIndexRoute
  ApiStatusesIndexRoute: typeof ApiStatusesIndexRoute
  ApiTagsIndexRoute: typeof ApiTagsIndexRoute
  ApiTasksIndexRoute: typeof ApiTasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/': {
      id: '/api/tasks/'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/': {
      id: '/api/tags/'
      path: '/api/tags'
      fullPath: '/api/tags'
      preLoaderRoute: typeof ApiTagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/statuses/': {
      id: '/api/statuses/'
      path: '/api/statuses'
      fullPath: '/api/statuses'
      preLoaderRoute: typeof ApiStatusesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-reports/': {
      id: '/api/daily-reports/'
      path: '/api/daily-reports'
      fullPath: '/api/daily-reports'
      preLoaderRoute: typeof ApiDailyReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$taskId': {
      id: '/api/tasks/$taskId'
      path: '/api/tasks/$taskId'
      fullPath: '/api/tasks/$taskId'
      preLoaderRoute: typeof ApiTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/$tagId': {
      id: '/api/tags/$tagId'
      path: '/api/tags/$tagId'
      fullPath: '/api/tags/$tagId'
      preLoaderRoute: typeof ApiTagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/statuses/$statusId': {
      id: '/api/statuses/$statusId'
      path: '/api/statuses/$statusId'
      fullPath: '/api/statuses/$statusId'
      preLoaderRoute: typeof ApiStatusesStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-reports/$date': {
      id: '/api/daily-reports/$date'
      path: '/api/daily-reports/$date'
      fullPath: '/api/daily-reports/$date'
      preLoaderRoute: typeof ApiDailyReportsDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-reports/$date/tasks': {
      id: '/api/daily-reports/$date/tasks'
      path: '/tasks'
      fullPath: '/api/daily-reports/$date/tasks'
      preLoaderRoute: typeof ApiDailyReportsDateTasksRouteImport
      parentRoute: typeof ApiDailyReportsDateRoute
    }
  }
}

interface ApiDailyReportsDateRouteChildren {
  ApiDailyReportsDateTasksRoute: typeof ApiDailyReportsDateTasksRoute
}

const ApiDailyReportsDateRouteChildren: ApiDailyReportsDateRouteChildren = {
  ApiDailyReportsDateTasksRoute: ApiDailyReportsDateTasksRoute,
}

const ApiDailyReportsDateRouteWithChildren =
  ApiDailyReportsDateRoute._addFileChildren(ApiDailyReportsDateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDailyReportsDateRoute: ApiDailyReportsDateRouteWithChildren,
  ApiStatusesStatusIdRoute: ApiStatusesStatusIdRoute,
  ApiTagsTagIdRoute: ApiTagsTagIdRoute,
  ApiTasksTaskIdRoute: ApiTasksTaskIdRoute,
  ApiDailyReportsIndexRoute: ApiDailyReportsIndexRoute,
  ApiStatusesIndexRoute: ApiStatusesIndexRoute,
  ApiTagsIndexRoute: ApiTagsIndexRoute,
  ApiTasksIndexRoute: ApiTasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
